-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Users"
(
    "Id" integer,
    "Email" character varying(50),
    "Password" "char",
    PRIMARY KEY ("Id")
);

CREATE TABLE public."SystemEmployees"
(
    "UserId" integer,
    "FirstName" character varying(50),
    "LastName" character varying(50),
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."Candidates"
(
    "UserId" integer,
    "FirstName" character varying(50),
    "LastName" character varying(50),
    "NationalityId" character varying(11),
    "DateOfBirth" character varying(4),
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."Employers"
(
    "UserId" integer,
    "CompanyName" character varying(200),
    "WebSite" character varying(100),
    "PhoneNumber" character varying(20),
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."JobPositions"
(
    "Id" integer,
    "PositionName" character varying(100),
    PRIMARY KEY ("Id")
);

CREATE TABLE public."CandidatesVerification"
(
    "Id" integer,
    "CandidateId" integer,
    "IsMernisVerified" boolean,
    "IsEmailVerified" boolean,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."EmployersVerification"
(
    "Id" integer,
    "EmployerId" integer,
    "IsEmailVerified" boolean,
    "IsSystemEmployeeVerified" boolean,
    PRIMARY KEY ("Id")
);

ALTER TABLE public."SystemEmployees"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Candidates"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."CandidatesVerification"
    ADD FOREIGN KEY ("CandidateId")
    REFERENCES public."Candidates" ("UserId")
    NOT VALID;


ALTER TABLE public."EmployersVerification"
    ADD FOREIGN KEY ("EmployerId")
    REFERENCES public."Employers" ("UserId")
    NOT VALID;

END;